name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      
      - name: Run action
        uses: ./
        with:
          upload: true
          share: true
    
          # cloud_project: <myworkspace/myproject>
          # cloud_api_token: <token>